Recursive Code To Get Java Code to Parse Json
nerdyninja/json-coder pull request #30
Opened 2020-01-13 10:53 UTC by vipul-08

2020-01-13 12:03 UTC, omkarprabhu-continuum commented
@vipul-08 
- Add your name in Contributors
- Change all the _nerdyninja_ specific URLs to _**prabhuomkar**_

I came across a bug (which is not a part of scope of this PR)

2020-01-13 12:17 UTC, prabhuomkar commented
@vipul-08 
- Add your name in Contributors
- Change all the _nerdyninja_ specific URLs to _**prabhuomkar**_

I came across a bug (which is not in the scope of this PR), will create an issue. Please try to fix it as well :)

2020-01-13 12:20 UTC, prabhuomkar requested changes
Need to add `<br>` after several lines.

2020-01-13 12:20 UTC, prabhuomkar commented on js/jsoncoder.js
> +  // Thanks for Reading :-)
Edit this line.
Replace it with some fancy quote :)

2020-01-13 12:20 UTC, prabhuomkar commented on js/jsoncoder.js
> +
Remove empty line

2020-01-14 13:23 UTC, vipul-08 commented
@prabhuomkar The changes are done. You can cross check and merge them.

2020-01-14 13:54 UTC, prabhuomkar approved these changes

2020-01-14 13:54 UTC, merged